<Label>:
	font_name:"10062.ttf"
<Final>:
	FloatLayout:

		canvas.before:
			Rectangle:
				pos:self.pos
				size:self.size			
				source:"pobedaa.png"
		Label:
			id:pobeda
			font_size:40
			pos_hint:{"top":.85,"right":.85}
			size_hint:.7,.2
			color:(0, 0, 0, 1)
			
		ImageButton:
			pos_hint:{"top":.95,"right":.75}
			size_hint:.5,.1
			source:"vern.png"
			on_press:
				app.build()
				app.change_screen("menu_screen")
				app.notpriz()
		